services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    volumes:
      # Use a named volume for database persistence across code updates
      - db_data:/usr/src/app/database
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    container_name: noorao_gpon_designer_backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    container_name: noorao_gpon_designer_frontend

volumes:
  db_data:
