services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      # Mount a directory for the database to ensure it persists correctly
      - ./server/database:/usr/src/app/database
    restart: unless-stopped
    container_name: pol_designer_backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    container_name: pol_designer_frontend
