name: CI

on:
  pull_request:
  push:
    branches: [ main, repo-hygiene ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend deps
        run: |
          npm ci
      - name: Build frontend
        run: |
          npm run build

      - name: Install backend deps
        working-directory: server
        run: |
          npm ci
      - name: Build backend
        working-directory: server
        run: |
          npm run build

      - name: Docker build (smoke)
        run: |
          docker build -t eltex-frontend .
          docker build -t eltex-backend ./server